In [5]:
import numpy as np

li=[1,2,3,4,[2,3]]

a=np.array(li)
type(a)
li

m=np.arange(0,100)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [30]:
nd2=np.random.randint(0,101,size=12)
nd3=np.random.randint(0,101,size=(3,3,3,3))
nd3[2][2][2][2]
nd3[2,2,2,2]

59

In [26]:
nd3.size
nd3.ndim
nd3.shape
nd3.dtype
nd3.itemsize
nd3.nbytes

324

In [47]:
n=np.array([[65,  7, 48],
       [88, 53, 64],
       [ 9, 44, 85]])
n[::,:]
n.reshape(3,3)

array([[65,  7, 48],
       [88, 53, 64],
       [ 9, 44, 85]])

In [62]:
n=np.arange(0,16).reshape(4,4)

h,i=np.vsplit(n,[2])
print(i)
print(h)

[[ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]


In [63]:
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
v=1+n
u=[1,2,3,4]

v+u

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16],
       [14, 16, 18, 20]])

In [73]:
m=np.ones((3,3))

m=np.arange(1)

In [74]:
m

array([], dtype=int32)

### Pandas

- Data Cleaning
- Data Transformation
- Data Analysis

**Notations**

- Series
- DataFrames

In [6]:
import pandas as pd

External1={'s1':55,'s2':66,'s3':77,'s4':99}
External2={'s1':22,'s2':33,'s3':43,'s4':78}

External1=pd.Series(External1)
External2=pd.Series(External2)
External1,External2

(s1    55
 s2    66
 s3    77
 s4    99
 dtype: int64, s1    22
 s2    33
 s3    43
 s4    78
 dtype: int64)

In [18]:
Final={'External1':External1,'External2':External2}
Final=pd.DataFrame(Final)
Final['External1']

s1    55
s2    66
s3    77
s4    99
Name: External1, dtype: int64

In [19]:
Final.columns

Index(['External1', 'External2'], dtype='object')

In [20]:
Final.values

array([[55, 22],
       [66, 33],
       [77, 43],
       [99, 78]], dtype=int64)

In [4]:
import pandas as pd
# Reading CSV files

filepath='DataFiles/Income.csv.txt'

incomedf=pd.read_csv(filepath)

incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [15]:
for row in incomedf.values:
    print(row[1],':',row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [23]:
# Average income of Arizona

sum=0

for i in range (2,11):
    sum+=incomedf.values[2,i]
    
sum/len(incomedf.values[2][2:])

47214.77777777778

In [33]:
sum=0
for i in range (0,5):
    sum+=incomedf.values[i,7]
# or
sum=0
for row in incomedf.values:
    sum+=row[-2]
    
sum/len(incomedf.values)

50038.8